name: CD- PROD
on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Get the right build name from the ./build directory for PROD deployment'    
        required: true
        default: 'build-adf-<timestamp>'


# Allows you to run this workflow manually from the Actions tab
permissions:
      id-token: write
      contents: write
      packages: write
jobs:

  deploy:
  # Deploy to prod environment AZ-WEUR-PROD-RNA-RG01
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print build name
        run: echo "The build name is ${{ github.event.inputs.build_name }}"
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ADF_LAB_KNAUF_UAT #AZ-WEUR-PROD-RNA-RG01 (6) your target ADF resource group name
          dataFactoryName: adfKnaufUat #AZ-WEUR-PROD-RNA-ADF01 (7) your target ADF name
          armTemplateFile: ./build/${{ github.event.inputs.build_name }}/ARMTemplateForFactory.json # (8) ARM template file name ARMTemplateForFactory.json
          armTemplateParametersFile: ./build/${{ github.event.inputs.build_name }}/ARMTemplateParametersForFactory.json # (9) ARM template parameters file name ARMTemplateParametersForFactory.json    
          #additionalParameters: factoryName=${{ vars.factoryName }} AZ_WEUR_XXX_RNA_KV01_properties_typeProperties_baseUrl=${{ vars.KV_baseUrl }} RNASA01_BRONZE_LKSVC01_properties_typeProperties_url=${{ vars.BRONZE_typeProperties_url }} RNASA01_SILVER_LKSVC01_properties_typeProperties_url= ${{ vars.SILVER_typeProperties_url }} SF_LKSVC01_properties_typeProperties_environmentUrl= ${{ vars.SF_environmentUrl }} SF_LKSVC01_properties_typeProperties_username= ${{ vars.SF_username }} SYNWS01_ARTIFACTS_LKSVC01_properties_typeProperties_endpoint= ${{ vars.SYN_endpoint}} AZ-WEUR-XXX-RNA-SA01-DFS-MPE01_properties_privateLinkResourceId = ${{ vars.DFS_privateLinkResourceId}} AZ-WEUR-XXX-RNA-SA01-DFS-MPE01_properties_groupId= ${{ vars.DFS_groupId}} AZ-WEUR-XXX-RNA-SYNWS01-DEV-MPE01_properties_privateLinkResourceId= ${{ vars.SYN_privateLinkResourceId}} AZ-WEUR-XXX-RNA-SYNWS01-DEV-MPE01_properties_groupId= ${{ vars.SYN_groupId}} AZ-WEUR-XXX-RNA-SYNWS01-SQL-MPE01_properties_privateLinkResourceId = ${{ vars.SQL_privateLinkResourceId}} AZ-WEUR-XXX-RNA-SYNWS01-SQL-MPE01_properties_groupId= ${{ vars.SQL_groupId}}

      - name: Notify Success
        if: success()
        run: echo "Artifact successfully deployed to PROD environment." 

  
