name: Create Release Branch
on: 
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release Branch
        run: |
          git checkout -b release
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git push origin release
