name: Create Release Branch
on: 
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  branch:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BUILD_PAT }}

      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ADF_LAB_KNAUF_PROD # (6) your target ADF resource group name
          dataFactoryName: adfKnaufPROD # (7) your target ADF name
          armTemplateFile: ./build/${{ github.event.inputs.build_name }}/ARMTemplateForFactory.json # (8) ARM template file name ARMTemplateForFactory.json
          #armTemplateParametersFile: ./build/${{ github.event.inputs.build_name }}/ARMTemplateParametersForFactory.json AZ-WEUR-Test-RNA-ADF01 
          # (9) ARM template parameters file name ARMTemplateParametersForFactory.json    

      - name: Create Release Branch
        run: |
          git checkout -b release
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git push origin release
