# This is a basic workflow to help you get started with Actions

name: UAT ADF WF

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Get the right build name from the ./build directory for UAT deployment'     
        required: true
        default: 'build-adf-<timestamp>'


  # Allows you to run this workflow manually from the Actions tab
permissions:
      id-token: write
      contents: write
      packages: write
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Build_Name: ${{ github.event.inputs.build_name }}" 
        

    
