# This is a basic workflow to help you get started with Actions

name: UAT ADF WF

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
permissions:
      id-token: write
      contents: write
      packages: write
