# This is a basic workflow to help you get started with Actions

name: cicd-dev
# Controls when the workflow will run
on:
  workflow_dispatch:
#Run only when the pull request is closed and it targets main branch
  pull_request:
    types: closed
    branches:
    - main
    paths-ignore:
      - '.github/**'
      - 'build/**'
      - 'README.md'
      - 'CODEOWNERS'

# Modify the default permissions granted to GITHUB_TOKEN.
permissions:
      id-token: write
      contents: write
      packages: write

jobs: 
  Build:
    runs-on: ubuntu-latest
    outputs:
      BUILD_NAME: ${{ steps.buildname.outputs.BUILD_NAME }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate build name with timestamp
        id: buildname
        run: echo "BUILD_NAME=build-adf-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        #   echo "BUILD_NAME=build-adf-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        #run: echo "::set-output name=BUILD_NAME::build-adf-$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"
      - name: Print build name
        run: |          
          echo "The build name is ${{ steps.buildname.outputs.BUILD_NAME }}"
     

      # Installs Node and the npm packages saved in your package.json file in the build
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.x

      #Caching (to cache the dependencies so the workflow execution time reduces)
      - name: Cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: deps-node-modules-$${{ hashFiles('**/package-lock.json')}}  

      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{github.workspace}}/build  # (1) provide the folder location of the package.json file

      # Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
      - name: Validate
        run: npm run build validate ${{github.workspace}}/ /subscriptions/73d4603c-76cc-4e1b-bed0-a3780c55b193/resourceGroups/ADF_LAB_KNAUF/providers/Microsoft.DataFactory/factories/DatafactoryForKnaufDemo 
        # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
        working-directory: ${{github.workspace}}/build  

      - name: Validate and Generate ARM template
        run: npm run build export ${{github.workspace}}/ /subscriptions/73d4603c-76cc-4e1b-bed0-a3780c55b193/resourceGroups/ADF_LAB_KNAUF/providers/Microsoft.DataFactory/factories/DatafactoryForKnaufDemo ${{ steps.buildname.outputs.BUILD_NAME }}  # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 
        working-directory: ${{github.workspace}}/build
  
      # In order to leverage the artifact in another job, we need to upload it with the upload action 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.buildname.outputs.BUILD_NAME }} # (4) use the same artifact name you used in the previous export step
          path: ${{github.workspace}}/build/${{ steps.buildname.outputs.BUILD_NAME }}
          
      #Commit updated builds (commit changes made in your workflow run directly to the repo)     
      - name: Commit the built artifact
        uses: EndBug/add-and-commit@v9
        with:
          message: 'commit artifact ${{ steps.buildname.outputs.BUILD_NAME }}'
          


  DeployToDevEnviornment:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Access Variable
        run: |
          echo "BUILD_NAME==${{ needs.Build.outputs.BUILD_NAME }}" 
        
      # We first download the previously uploaded artifact so we can leverage it later in the release job  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ needs.Build.outputs.BUILD_NAME }} # (5) Artifact name  

        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ADF_LAB_KNAUF # (6) your target ADF resource group name
          dataFactoryName: DatafactoryForKnaufDemo # (7) your target ADF name
          armTemplateFile: ARMTemplateForFactory.json # (8) ARM template file name ARMTemplateForFactory.json
          #armTemplateParametersFile: ./build/${{ github.event.inputs.build_name }}/ARMTemplateParametersForFactory.json AZ-WEUR-Test-RNA-ADF01 
          # (9) ARM template parameters file name ARMTemplateParametersForFactory.json  
            
            

                  
      - name: Notify Success
        if: success()
        run: echo "Artifact successfully built and deployed to Dev environment."  
  
    
