name: Find and Replace JSON

on:
  workflow_dispatch:

jobs:
  find_and_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find and Replace in JSON
      run: |
        # Find and replace the text in your JSON file using jq
        #PrintQuotesAsString = "\"linkedInfo\":{\"resourceId\":\"/subscriptions/1e97185d-6892-4844-9688-e3b26adccca2/resourcegroups/AZ-WEUR-PROD-RNA-RG01/providers/Microsoft.DataFactory/factories/AZ-WEUR-PROD-RNA-ADF01/integrationruntimes/SHIR01-RUN01\",}" 
        jq '. + [ { "entry": "10.20.17.0/24", "comment": "test ip3" }, { "entry": "10.20.18.0/24", "comment": "test ip4" } ]'
        #cat ./ARMTemplateForFactory.json |  jq '.resources[] | select (.name == "[concat(parameters('\''factoryName'\''), '\''/SHIR01-RUN01'\'')]") .properties.typeProperties = "${{ vars.SHIR}}"'     
        #jq --arg search "SHIR01-RUN01" --arg replace "SHIR01-RUN02" ' ./ARMTemplateParametersForFactory.json > tmp.json &&  mv tmp.json ./ARMTemplateParametersForFactory.json
        
      working-directory: ${{ github.workspace }}
    
    # - name: Commit and push changes
    #   run: |
    #     git config user.name "Tara-Morovatdar"
    #     git config user.email "t.morovatdar@gmail.com"
    #     git add ./ARMTemplateParametersForFactory.json
    #     git commit -m "Update JSON file"
    #     git push
