name: Find and Replace JSON

on:
  workflow_dispatch:

jobs:
  find_and_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find and Replace in JSON
      run: |
        # Define the search and replace strings
        SEARCH_STRING=""name": "[concat(parameters('factoryName'), '/SHIR01-RUN01')]","
        REPLACE_STRING= ""name": "[concat(parameters('factoryName'), '/SHIR01-RUN02')]","

        # Find and replace the text in your JSON file using jq
        jq --arg search "$SEARCH_STRING" --arg replace "$REPLACE_STRING" '. | walk(if type == "string" then if . == $search then $replace else . end else . end)' ./build/build-adf-20231105173635/ARMTemplateParametersForFactory.json > tmp.json
        mv tmp.json ./build/build-adf-20231105173635/ARMTemplateParametersForFactory.json
        #echo ./build/${{ github.event.client_payload.BUILD_NAME }}/ARMTemplateParametersForFactory.json
      working-directory: ${{ github.workspace }}
    
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add your-json-file.json
        git commit -m "Update JSON file"
        git push
