name: Calculate Timestamp for 30 Days Ago

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor for changes

jobs:
  calculate_timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Calculate Timestamp
      id: timestamp
      run: |
        # Calculate the timestamp for 30 days ago (in seconds since the epoch)
        timestamp1=$(date -d "30 days ago" +%Y%m%d%H%M%S)
        timestamp2=$(date -d "15 days ago" +%Y%m%d%H%M%S)
        # Output the timestamp as an action output
        echo "::set-output name=timestamp1::$timestamp1"
        echo "::set-output name=timestamp2::$timestamp2"

    - name: Display Timestamp
      run: |
        time_diff= $((timestamp2 - timestamp1))
        echo "::set-output name=time_diff::$time_diff_seconds"
        # Retrieve the timestamp calculated in the previous step
        #TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}
        
        # Display the timestamp
        #echo "Timestamp for 30 days ago: $TIMESTAMP"
