# This is a basic workflow to help you get started with Actions

name: Test WF

on:
  workflow_dispatch:
  # pull_request:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/**'
  # Allows you to run this workflow manually from the Actions tab
permissions:
      id-token: write
      contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    persistCredentials: True
  - task: ArchiveFiles@2
    displayName: Archive README.md
    inputs:
      rootFolderOrFile: README.md
      archiveFile: $(Build.ArtifactStagingDirectory)\zipfolder/$(Build.BuildId).zip
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\zipfolder
  - task: DownloadBuildArtifacts@1
    displayName: Download Build Artifacts
    inputs:
      artifactName: drop
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: >-
        cd $(System.ArtifactsDirectory)\zipfolder

        git config --global user.email "xxxxx"

        git config --global user.name "xxxxx"

        git init

        git add .

        git commit -m "123"

        git remote add origin https://$(System.AccessToken)@dev.azure.com/orgname/testpro1/_git/testpro4

        git push https://$(System.AccessToken)@dev.azure.com/orgname/testpro1/_git/testpro4
...
