---

name: test wf

on:  # yamllint disable-line rule:truthy
  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - name: Build ROM
        run: |
          mkdir artifact
          echo hi > world.txt
          cp build/world.txt artifact/.

      - name: Archive Build Result
        uses: actions/upload-artifact@v3
        with:
          name: ROM Image
          path: artifact
